<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../library/Zend149/Service/Bitly.php';

/**
 * Test class for Zend149_Service_Bitly.
 * Generated by PHPUnit on 2010-09-09 at 13:14:32.
 */
class Zend149_Service_BitlyTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Zend149_Service_Bitly
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Zend149_Service_Bitly;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        unset($this->object);
    }

    /**
     * @todo Implement testShorten().
     */
    public function testShorten()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testExpand().
     */
    public function testExpand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetApiKey().
     */
    public function testGetApiKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetApiKey().
     */
    public function testSetApiKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetUserId().
     */
    public function testGetUserId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetUserId().
     */
    public function testSetUserId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * Tests the format setter with valid formats
     *
     * @covers Zend149_Service_Bitly::setFormat
     */
    public function testSetValidFormat()
    {
        $bitly = $this->object;

        $bitly->setFormat('object');
        $this->assertAttributeEquals('object', '_format', $bitly);

        $bitly->setFormat('json');
        $this->assertAttributeEquals('json', '_format', $bitly);
    }

    /**
     * Tests the format setter with an invalid format. An Exception should come up.
     *
     * @covers Zend149_Service_Bitly::setFormat
     * @expectedException Zend149_Service_Bitly_Exception
     */
    public function testSetInvalidFormat()
    {
        $bitly = $this->object;
        $bitly->setFormat('hurz');
    }

    /**
     * Test the format getter
     *
     * @covers Zend149_Service_Bitly::getFormat
     */
    public function testGetFormat()
    {
        $bitly = $this->object;
        $expected = 'json';

        $bitly->setFormat($expected);

        $result = $bitly->getFormat();
        $this->assertEquals($expected, $result);
    }

    /**
     * Test the format getter with default value
     *
     * @covers Zend149_Service_Bitly::getFormat
     */
    public function testGetDefaultFormat()
    {
        $bitly = $this->object;
        $result = $bitly->getFormat();
        $this->assertEquals('object', $result);
    }
}
